"""PR creation service — creates GitHub pull requests via installation tokens."""
import asyncio
from typing import Any

import requests

from app.utils.logger import get_logger

logger = get_logger(__name__)

GITHUB_API_BASE = "https://api.github.com"


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "self-healing-ci-agent",
    }


def create_pull_request_on_github(
    repo_full_name: str,
    installation_token: str,
    title: str,
    body: str,
    head: str,
    base: str = "main",
) -> dict[str, Any]:
    """Create a pull request on GitHub.

    Args:
        repo_full_name: Full repository name (e.g. "owner/repo").
        installation_token: GitHub installation access token.
        title: PR title.
        body: PR body/description.
        head: The name of the branch where changes are implemented.
        base: The name of the branch you want the changes pulled into.

    Returns:
        Dict with PR metadata: number, url, state, title.
    """
    url = f"{GITHUB_API_BASE}/repos/{repo_full_name}/pulls"
    resp = requests.post(
        url,
        headers=_headers(installation_token),
        json={"title": title, "body": body, "head": head, "base": base},
    )
    if resp.status_code == 422:
        error_data = resp.json()
        logger.warning(f"GitHub PR creation failed (422): {error_data}")
        return {"number": None, "html_url": None, "state": "error", "title": title}
    resp.raise_for_status()
    data = resp.json()
    return {
        "number": data.get("number"),
        "html_url": data.get("html_url"),
        "state": data.get("state", "open"),
        "title": data.get("title", ""),
    }


async def create_pull_request_async(
    repo_full_name: str,
    installation_token: str,
    title: str,
    body: str,
    head: str,
    base: str = "main",
) -> dict[str, Any]:
    """Async wrapper for create_pull_request_on_github."""
    return await asyncio.to_thread(
        create_pull_request_on_github,
        repo_full_name,
        installation_token,
        title,
        body,
        head,
        base,
    )


def generate_pr_title(fix_summary: str, error_category: str | None = None) -> str:
    """Generate a standardized PR title.

    Format: [Auto-Heal] <short failure summary>
    """
    if fix_summary:
        summary = fix_summary.strip().rstrip(".")
        if len(summary) > 72:
            summary = summary[:69] + "..."
        return f"[Auto-Heal] {summary}"
    return "[Auto-Heal] Automated fix for CI/CD failure"


def generate_pr_description(
    fix_summary: str,
    root_cause: str,
    modified_files: list[str],
    validation_stages: list[dict[str, Any]] | None = None,
    confidence_score: float | None = None,
) -> str:
    """Generate a structured PR description.

    Sections: Summary, Root Cause, Fix Applied, Validation Results, Safety Assessment.
    """
    parts: list[str] = []

    # Summary
    parts.append("## Summary")
    parts.append(fix_summary or "Automated fix generated by Self-Healing CI Agent.")
    parts.append("")

    # Root Cause
    parts.append("## Root Cause")
    parts.append(root_cause or "Unknown — root cause analysis was not available.")
    parts.append("")

    # Fix Applied
    parts.append("## Fix Applied")
    if modified_files:
        parts.append("The following files were modified:")
        for f in modified_files:
            parts.append(f"- `{f}`")
    else:
        parts.append("No specific files listed (see patch for details).")
    parts.append("")

    # Validation Results
    parts.append("## Validation Results")
    if validation_stages:
        for stage in validation_stages:
            name = stage.get("stage", stage.get("name", "unknown")).replace("_", " ").title()
            status = stage.get("status", "unknown")
            parts.append(f"- **{name}**: {status}")
        parts.append("")
    else:
        parts.append("Validation completed. See investigation for full results.")
        parts.append("")

    # Confidence / Safety
    parts.append("## Safety Assessment")
    if confidence_score is not None:
        if confidence_score >= 0.7:
            parts.append(f"Confidence score: **{confidence_score:.0%}** — High confidence. "
                         "The fix has passed validation and is considered safe to merge.")
        elif confidence_score >= 0.4:
            parts.append(f"Confidence score: **{confidence_score:.0%}** — Moderate confidence. "
                         "The fix has passed validation but manual review is recommended.")
        else:
            parts.append(f"Confidence score: **{confidence_score:.0%}** — Low confidence. "
                         "Manual review strongly recommended before merging.")
    else:
        parts.append("Fix has passed validation checks. Manual review recommended before merging.")
    parts.append("")

    parts.append("---")
    parts.append("_This pull request was automatically generated by the Self-Healing CI Agent._")

    return "\n".join(parts)
