import datetime
from typing import Any, Dict, List

from app.utils.logger import get_logger

logger = get_logger(__name__)


def generate_commit_message(
    fix_summary: str,
    root_cause: str = "",
    modified_files: Optional[List[str]] = None,
) -> str:
    """Generate a standardized commit message from fix details.

    Args:
        fix_summary: Summary of the fix applied.
        root_cause: Root cause analysis text.
        modified_files: List of files modified in the fix.

    Returns:
        Commit message string.
    """
    title = f"fix: {fix_summary[:72].rstrip('.')}"
    if len(fix_summary) > 72:
        title = title[:69] + "..."

    body_parts: List[str] = []
    if root_cause:
        body_parts.append(f"Root cause: {root_cause}")
    if modified_files:
        body_parts.append("Modified files:")
        for f in modified_files:
            body_parts.append(f"  - {f}")

    body = "\n".join(body_parts) if body_parts else "Automated fix generated by Self-Healing CI Agent."

    return f"{title}\n\n{body}"


async def create_commit(
    message: str,
    dry_run: bool = True,
) -> Dict[str, Any]:
    """Simulate or prepare a commit.

    In dry_run mode, only validates the commit message and structure.

    Args:
        message: Commit message.
        dry_run: If True, only simulates.

    Returns:
        Dict with keys: committed (bool), message (str), dry_run (bool), commit_hash (str).
    """
    if not message or not message.strip():
        return {
            "committed": False,
            "message": "",
            "dry_run": dry_run,
            "commit_hash": "",
            "error": "Empty commit message.",
        }

    if dry_run:
        logger.info("Dry run: commit would be created")
        return {
            "committed": True,
            "message": message,
            "dry_run": True,
            "commit_hash": "SIMULATED_COMMIT_HASH",
            "note": "Simulated commit — no changes pushed (dry run).",
        }

    logger.warning("Real commit creation not yet implemented")
    return {
        "committed": False,
        "message": message,
        "dry_run": False,
        "commit_hash": "",
        "error": "Real commit creation requires repository clone and write access.",
    }
