from typing import Any, Dict, List, Optional

from app.config.settings import settings
from app.utils.logger import get_logger
from app.utils.deepseek_client import DeepSeekClient
from app.prompts.pr_prompt import build_pr_prompt, parse_pr_output

logger = get_logger(__name__)


class PRGenerator:
    """Generates PR titles, descriptions, and change summaries from fix details.

    Uses DeepSeek when available, falls back to rule-based generation.
    """

    def __init__(self):
        self._deepseek: Optional[DeepSeekClient] = None

    async def generate(
        self,
        root_cause: str,
        fix_summary: str,
        error_category: str,
        modified_files: List[str],
        validation: str,
        review: str,
    ) -> Dict[str, Any]:
        """Generate PR content from fix and validation details.

        Args:
            root_cause: Root cause analysis text.
            fix_summary: Summary of the generated fix.
            error_category: Error category string.
            modified_files: List of modified file paths.
            validation: Validation report text.
            review: Review report text.

        Returns:
            Dict with keys: title, description, change_summary.
        """
        prompt = build_pr_prompt(
            root_cause=root_cause,
            fix_summary=fix_summary,
            error_category=error_category,
            modified_files=modified_files,
            validation=validation,
            review=review,
        )

        llm_output = await self._call_llm(prompt["system"], prompt["user"])
        parsed = parse_pr_output(llm_output) if llm_output else {}

        if not parsed.get("title"):
            return self._fallback_generate(fix_summary, modified_files)

        return parsed

    async def _call_llm(self, system_prompt: str, user_prompt: str) -> Optional[str]:
        if not settings.deepseek_api_key:
            logger.warning("No DeepSeek API key — returning PR fallback")
            return None

        try:
            if self._deepseek is None:
                self._deepseek = DeepSeekClient()
            return await self._deepseek.generate_response(
                prompt=user_prompt,
                system_prompt=system_prompt,
                temperature=0.3,
                max_tokens=2048,
            )
        except Exception as e:
            logger.error(f"LLM call failed during PR generation: {e}")
            return None

    def _fallback_generate(
        self,
        fix_summary: str,
        modified_files: List[str],
    ) -> Dict[str, Any]:
        """Generate rule-based PR content when LLM is unavailable.

        Args:
            fix_summary: Summary of the generated fix.
            modified_files: List of modified file paths.

        Returns:
            Dict with keys: title, description, change_summary.
        """
        title = f"fix: {fix_summary[:60].rstrip('.')}" if fix_summary else "fix: automated fix for CI/CD failure"
        if len(title) > 72:
            title = title[:69] + "..."

        files_list = "\n".join(f"- {f}" for f in modified_files) if modified_files else "- (see patch)"
        description = (
            f"## Summary\n{fix_summary or 'Automated fix generated by Self-Healing CI Agent.'}\n\n"
            f"## Files Modified\n{files_list}\n\n"
            "## Validation\nValidation passed. See workflow logs for details.\n\n"
            "## Notes\nThis PR was automatically generated by the Self-Healing CI Agent."
        )
        change_summary = files_list if modified_files else "- No specific files listed"

        return {
            "title": title,
            "description": description,
            "change_summary": change_summary,
        }
